parameters:
#    sice_hola.example.class: SICE\HolaBundle\Example

services:
#    sice_hola.example:
#        class: %sice_hola.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
